class_name DataRegistryPaths
extends RefCounted

# Auto-generated by tools/build_data_manifest.py — do not edit by hand.
# Preloads ensure data/*.tres are bundled in exported exe/apk (DirAccess alone does not).

const CARD_RESOURCES: Array = [
	preload("res://data/cards/assassins_approach.tres"),
	preload("res://data/cards/battle_axe.tres"),
	preload("res://data/cards/black_flame.tres"),
	preload("res://data/cards/bloodhounds_step.tres"),
	preload("res://data/cards/bloody_slash.tres"),
	preload("res://data/cards/buckler.tres"),
	preload("res://data/cards/catch_flame.tres"),
	preload("res://data/cards/club.tres"),
	preload("res://data/cards/comet.tres"),
	preload("res://data/cards/crimson_flask.tres"),
	preload("res://data/cards/destined_death.tres"),
	preload("res://data/cards/flame_grant_me_strength.tres"),
	preload("res://data/cards/glintstone_arc.tres"),
	preload("res://data/cards/glintstone_pebble.tres"),
	preload("res://data/cards/glintstone_stars.tres"),
	preload("res://data/cards/great_knife.tres"),
	preload("res://data/cards/guard_counter.tres"),
	preload("res://data/cards/halberd.tres"),
	preload("res://data/cards/heal.tres"),
	preload("res://data/cards/heater_shield.tres"),
	preload("res://data/cards/heavy_charge.tres"),
	preload("res://data/cards/hoarfrost_stomp.tres"),
	preload("res://data/cards/lions_claw.tres"),
	preload("res://data/cards/longbow.tres"),
	preload("res://data/cards/longsword.tres"),
	preload("res://data/cards/magic_glintblade.tres"),
	preload("res://data/cards/rock_sling.tres"),
	preload("res://data/cards/rotten_breath.tres"),
	preload("res://data/cards/scimitar.tres"),
	preload("res://data/cards/shard_spiral.tres"),
	preload("res://data/cards/storm_blade.tres"),
	preload("res://data/cards/twinblade.tres"),
	preload("res://data/cards/uchigatana.tres"),
	preload("res://data/cards/urgent_heal.tres"),
	preload("res://data/cards/volcano_pot.tres"),
]

const ORIGIN_RESOURCES: Array = [
	preload("res://data/origins/astrologer.tres"),
	preload("res://data/origins/prophet.tres"),
	preload("res://data/origins/samurai.tres"),
	preload("res://data/origins/vagabond.tres"),
	preload("res://data/origins/warrior.tres"),
	preload("res://data/origins/wretch.tres"),
]

const ACT_RESOURCES: Array = [
	preload("res://data/acts/limgrave.tres"),
	preload("res://data/acts/liurnia.tres"),
	preload("res://data/acts/stormveil.tres"),
]

const GRACE_OPTION_RESOURCES: Array = [
	preload("res://data/grace_options/ash_replace.tres"),
	preload("res://data/grace_options/clarity.tres"),
	preload("res://data/grace_options/destined_death.tres"),
	preload("res://data/grace_options/forge_etch.tres"),
	preload("res://data/grace_options/kindling.tres"),
	preload("res://data/grace_options/level_up.tres"),
	preload("res://data/grace_options/memory_stone.tres"),
	preload("res://data/grace_options/purge.tres"),
	preload("res://data/grace_options/rest.tres"),
	preload("res://data/grace_options/vitality.tres"),
	preload("res://data/grace_options/weapon_upgrade.tres"),
]

const RELIC_RESOURCES: Array = [
	preload("res://data/relics/ancestral_spirit.tres"),
	preload("res://data/relics/azurs_staff.tres"),
	preload("res://data/relics/blood_lord_joy.tres"),
	preload("res://data/relics/cerulean_medallion.tres"),
	preload("res://data/relics/crimson_amulet.tres"),
	preload("res://data/relics/erdtree_favor.tres"),
	preload("res://data/relics/erdtree_gift.tres"),
	preload("res://data/relics/gold_scarab.tres"),
	preload("res://data/relics/greatshield_talisman.tres"),
	preload("res://data/relics/green_turtle_talisman.tres"),
	preload("res://data/relics/marikas_brand.tres"),
	preload("res://data/relics/serpentbone_talisman.tres"),
	preload("res://data/relics/starscourge_prosthesis.tres"),
	preload("res://data/relics/twohanded_sword_badge.tres"),
]

const EVENT_RESOURCES: Array = [
	preload("res://data/events/echo_of_last_run.tres"),
	preload("res://data/events/limgrave_beggar.tres"),
	preload("res://data/events/limgrave_corpse.tres"),
	preload("res://data/events/limgrave_corpse_cache.tres"),
	preload("res://data/events/limgrave_frenzy_graffiti.tres"),
	preload("res://data/events/limgrave_gambler.tres"),
	preload("res://data/events/limgrave_misguided_sheep.tres"),
	preload("res://data/events/limgrave_smithing_table.tres"),
	preload("res://data/events/liurnia_crystal_crab.tres"),
	preload("res://data/events/liurnia_drowned.tres"),
	preload("res://data/events/liurnia_gambler.tres"),
	preload("res://data/events/liurnia_lake_chest.tres"),
	preload("res://data/events/liurnia_scholar.tres"),
	preload("res://data/events/liurnia_scholar_reward.tres"),
	preload("res://data/events/liurnia_shabriri_grape.tres"),
	preload("res://data/events/stormveil_armory.tres"),
	preload("res://data/events/stormveil_armory_inner.tres"),
	preload("res://data/events/stormveil_cursed_altar.tres"),
	preload("res://data/events/stormveil_deserter.tres"),
	preload("res://data/events/stormveil_rusty_lever.tres"),
	preload("res://data/events/stormveil_shrine.tres"),
]

const MERCHANT_OFFER_RESOURCES: Array = [
	preload("res://data/merchant_offers/ash_replace.tres"),
	preload("res://data/merchant_offers/blood_vial.tres"),
	preload("res://data/merchant_offers/curio_card.tres"),
	preload("res://data/merchant_offers/kindling_sale.tres"),
	preload("res://data/merchant_offers/memory_stone.tres"),
	preload("res://data/merchant_offers/refill_flasks.tres"),
	preload("res://data/merchant_offers/remove_card.tres"),
	preload("res://data/merchant_offers/scrap_paper.tres"),
	preload("res://data/merchant_offers/smithing_stone_1.tres"),
	preload("res://data/merchant_offers/smithing_stone_2.tres"),
	preload("res://data/merchant_offers/smithing_stone_3.tres"),
]

const ENEMY_RESOURCES: Array = [
	preload("res://data/enemies/academy_glintstone_sorcerer.tres"),
	preload("res://data/enemies/caelid_mercenary.tres"),
	preload("res://data/enemies/fallingstar_beast.tres"),
	preload("res://data/enemies/gargoyle_knight.tres"),
	preload("res://data/enemies/geirik_knight.tres"),
	preload("res://data/enemies/geirik_soldier.tres"),
	preload("res://data/enemies/gravekeeper_dualrander.tres"),
	preload("res://data/enemies/kaguth.tres"),
	preload("res://data/enemies/kaguth_chief.tres"),
	preload("res://data/enemies/kindred_of_rot.tres"),
	preload("res://data/enemies/margit.tres"),
	preload("res://data/enemies/misbegotten.tres"),
	preload("res://data/enemies/mohg_lovula.tres"),
	preload("res://data/enemies/stoneminer.tres"),
	preload("res://data/enemies/stoneminer_fiend.tres"),
	preload("res://data/enemies/tree_sentinel.tres"),
	preload("res://data/enemies/warhound_of_famiazurla.tres"),
	preload("res://data/enemies/wild_wolf.tres"),
]

const GROUP_RESOURCES: Array = [
	preload("res://data/enemy_groups/academy_scholars.tres"),
	preload("res://data/enemy_groups/elite_soldier_swarm.tres"),
	preload("res://data/enemy_groups/gargoyle_watch.tres"),
	preload("res://data/enemy_groups/gravekeeper_party.tres"),
	preload("res://data/enemy_groups/kaguth_raiders.tres"),
	preload("res://data/enemy_groups/kindred_of_rot_pair.tres"),
	preload("res://data/enemy_groups/mercenary_duo.tres"),
	preload("res://data/enemy_groups/rot_incursion.tres"),
	preload("res://data/enemy_groups/soldier_patrol.tres"),
	preload("res://data/enemy_groups/wolf_pack.tres"),
]

const WEAPON_RESOURCES: Array = [
	preload("res://data/weapons/battle_axe_w.tres"),
	preload("res://data/weapons/club_w.tres"),
	preload("res://data/weapons/dual_scimitar_w.tres"),
	preload("res://data/weapons/finger_seal_w.tres"),
	preload("res://data/weapons/greatsword_w.tres"),
	preload("res://data/weapons/halberd_w.tres"),
	preload("res://data/weapons/heater_shield_w.tres"),
	preload("res://data/weapons/longbow_w.tres"),
	preload("res://data/weapons/longsword_w.tres"),
	preload("res://data/weapons/staff_w.tres"),
	preload("res://data/weapons/uchigatana_w.tres"),
]

