"""Generate scripts/core/DataRegistryPaths.gd (UTF-8). Run after adding data/**/*.tres."""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
OUT = ROOT / "scripts" / "core" / "DataRegistryPaths.gd"

FOLDERS = {
    "CARD_RESOURCES": "cards",
    "ORIGIN_RESOURCES": "origins",
    "ACT_RESOURCES": "acts",
    "GRACE_OPTION_RESOURCES": "grace_options",
    "RELIC_RESOURCES": "relics",
    "EVENT_RESOURCES": "events",
    "MERCHANT_OFFER_RESOURCES": "merchant_offers",
    "ENEMY_RESOURCES": "enemies",
    "GROUP_RESOURCES": "enemy_groups",
    "WEAPON_RESOURCES": "weapons",
}


def _files(folder: str) -> list[str]:
    d = DATA / folder
    if not d.is_dir():
        return []
    return sorted(p.name for p in d.glob("*.tres") if not p.name.startswith("."))


def _preload_lines(folder: str, files: list[str]) -> list[str]:
    return [f'\tpreload("res://data/{folder}/{name}"),' for name in files]


def main() -> None:
    lines = [
        "class_name DataRegistryPaths",
        "extends RefCounted",
        "",
        "# Auto-generated by tools/build_data_manifest.py — do not edit by hand.",
        "# Preloads ensure data/*.tres are bundled in exported exe/apk (DirAccess alone does not).",
        "",
    ]
    total = 0
    for const_name, folder in FOLDERS.items():
        files = _files(folder)
        total += len(files)
        lines.append(f"const {const_name}: Array = [")
        if files:
            lines.extend(_preload_lines(folder, files))
        lines.append("]")
        lines.append("")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUT} ({total} preloads)")


if __name__ == "__main__":
    main()
